title: Daily Report
email: marketing@binary.com
description: > 
  Daily Report
baseurl: "" 
url: "https://dailyreport.binary.com" 
affurl: ""
twitter_username: 
github_username:  

markdown: kramdown
gems:
  - jekyll-feed